export interface Metric {
  value: string;
  label: { en: string; es: string };
}

export interface Project {
  id: string;
  slug: string;
  number: string;
  isLab: boolean;
  industry: { en: string; es: string };
  year: string;
  role: { en: string; es: string };
  confidentiality: { en: string; es: string };
  title: { en: string; es: string };
  subtitle: { en: string; es: string };
  hook: { en: string; es: string };
  overview: { en: string; es: string };
  context: { en: string; es: string };
  myRole: { en: string; es: string };
  whatMadeItInteresting: { en: string; es: string };
  howIApproached: { en: string; es: string };
  keyDecisions: { en: string; es: string };
  outcome: { en: string; es: string };
  learned: { en: string; es: string };
  metrics: Metric[];
  tags: string[];
  imageBg: string;
  images: {
    hero: string[];
    processMap: string;
    artifacts: string;
    impact: string;
  };
}

export const projects: Project[] = [
  {
    id: 'quoting-rewired',
    slug: 'quoting-rewired',
    number: '01',
    isLab: false,
    industry: { en: 'Insurance', es: 'Seguros' },
    year: '2024–2025',
    role: { en: 'UX/UI & Interaction Design Lead', es: 'Lead UX/UI & Diseño de Interacción' },
    confidentiality: { en: 'Anonymized (NDA)', es: 'Anonimizado (NDA)' },
    title: { en: 'Quoting, rewired.', es: 'Cotizar, repensado.' },
    subtitle: { en: 'Discovery and AI design for an enterprise quotation tool.', es: 'Discovery y diseño de IA para una herramienta enterprise de cotización.' },
    hook: { en: 'How do you redesign a tool everyone uses but nobody trusts?', es: '¿Cómo rediseñas una herramienta que todos usan pero nadie confía?' },
    overview: {
      en: `This project started with a tool that advisors technically needed, but no longer trusted. The quotation platform was central to the sales process: advisors used it to configure plans, compare scenarios and prepare client-facing proposals. In practice, many of them had moved part of that work to Excel because the legacy system crashed, felt rigid and created doubts around whether the final output would match what they had configured.\n\nMy role was to help rethink the experience from the ground up: understand how advisors actually sell, define the interaction architecture of the new quoting flow and design how AI should support the process without taking control away from the user. The result was a mobile-first quotation experience with AI-powered recommendations, real-time comparison, validation logic and clearer proposal generation. After validation, the tool moved from a negative NPS to a strongly positive one, with a 90.2 SUS score.`,
      es: `Este proyecto partió de un problema muy concreto: los asesores ya no confiaban en la herramienta que usaban para cotizar.\n\nLa plataforma era clave para vender seguros de vida, pero en la práctica muchos asesores habían terminado trabajando en Excel porque el sistema anterior fallaba, no era útil en campo y generaba dudas sobre la información final. El reto no era hacer una interfaz más moderna. Había que reconstruir confianza en una herramienta crítica para el negocio.\n\nMi trabajo fue liderar el diseño UX/UI y la arquitectura de interacción de una nueva experiencia de cotización, integrando recomendaciones asistidas por IA, comparación en tiempo real, validaciones y una forma más clara de generar propuestas para clientes.\n\nEl resultado fue una herramienta mucho más confiable para los asesores: el NPS pasó de −6.7% a 66.7%, el SUS llegó a 90.2 y el 100% de los asesores en la validación dijo que la recomendaría.`,
    },
    context: {
      en: `The client is one of the largest life insurance providers in its market. Its commercial model depends heavily on a national network of independent financial advisors who need to build credible, personalized quotations in front of clients.\n\nThat context mattered because the quotation tool was not a back-office system. It was part of the advisor's sales conversation. When the platform failed, the advisor did not just lose time. They lost confidence in front of the client.\n\nThe existing tool had several issues: crashes, inconsistent data between quotation and policy issuance, limited mobility, heavy forms and little clarity around how calculations were being made. Advisors had created their own workarounds, especially spreadsheets, because they felt they could control the process better outside the system. The challenge was not simply to modernize a legacy interface. The real problem was trust.`,
      es: `La compañía depende de una red nacional de asesores financieros que construyen, comparan y presentan cotizaciones a clientes. Eso la convertía en parte directa de la conversación comercial.\n\nCuando el sistema fallaba, el impacto iba más allá de perder tiempo. El asesor perdía seguridad frente al cliente. Tenía que validar datos por fuera, hacer cálculos paralelos o apoyarse en hojas de cálculo para compensar lo que la plataforma no resolvía bien.\n\nEl problema estaba en varias capas: caídas frecuentes, inconsistencias entre cotización y emisión, cero movilidad, formularios pesados y poca claridad sobre la lógica de los cálculos.\n\nLa nueva experiencia tenía que ordenar todo eso sin simplificar de más un proceso financiero que, por naturaleza, es complejo.`,
    },
    myRole: {
      en: `I led UX/UI and interaction design for the quotation experience. My work focused on four areas: structuring the full quotation flow, from client profiling to plan selection, comparison and proposal generation; defining how AI recommendations, conversational input and validation alerts should appear inside the advisor's natural workflow; translating advanced interaction concepts into clear UX specifications that product and engineering teams could actually build; and participating in usability testing with real advisors and turning findings into concrete design iterations.\n\nI worked with strategy, research, data science and engineering teams. My main responsibility was making sure the product vision became an experience that was clear enough for advisors and realistic enough for implementation.`,
      es: `Lideré el diseño UX/UI y la arquitectura de interacción del flujo de cotización.\n\nMe enfoqué en estructurar la experiencia completa: perfil del cliente, selección de planes, configuración de coberturas, comparación, validaciones y generación de propuesta.\n\nTambién diseñé cómo debía integrarse la IA dentro del flujo. Como una capa de apoyo presente en los momentos donde realmente podía ayudar: recomendaciones, alertas, explicaciones y atajos conversacionales.\n\nParticipé en pruebas con asesores reales y traduje los hallazgos en ajustes concretos de diseño. Mi responsabilidad era que la experiencia fuera clara para usuarios expertos, útil para el negocio y viable para los equipos que tenían que construirla.`,
    },
    whatMadeItInteresting: {
      en: `The tool had to earn trust again. Advisors had already learned not to depend on the old system for high-stakes moments. That made the design problem very different from a normal redesign. A cleaner interface was not enough. The product needed to show what was happening, explain why a recommendation made sense and reduce the feeling that the system could fail at any moment.\n\nAI needed to support expertise, not replace it. One of the strongest requests from advisors was an AI feature that could suggest the right product for a client. But advisors are specialists. They do not want a black box telling them what to sell. That changed the design direction. AI could recommend, validate and accelerate, but the final decision had to stay with the advisor.\n\nThe ecosystem was fragmented. Quotation, policy issuance, client data and reporting lived in different places. The new interface had to feel like one coherent flow even if the backend reality was more complex. The work was about designing clarity on top of fragmentation.`,
      es: `Lo más interesante era que el problema no era visual. Era de confianza.\n\nLos asesores necesitaban una herramienta que les ayudara a vender con más seguridad, explicar mejor una recomendación y sentir que el sistema no les iba a fallar en medio de una conversación con un cliente.\n\nLa IA también hacía el reto más delicado. Había mucho interés en que el sistema recomendara el producto ideal, pero los asesores no querían una caja negra. Son especialistas. Necesitaban entender el razonamiento, no solo recibir una sugerencia.\n\nEso definió una postura importante: la IA podía acelerar, validar y proponer, pero la decisión final tenía que quedarse con el asesor.`,
    },
    howIApproached: {
      en: `We started by understanding how advisors actually worked, not only what they said they needed, but what they did when the tool failed: the spreadsheets they built, the shortcuts they used, the information they double-checked and the moments where they avoided using the platform altogether. A key insight was that advisors were not asking for a better app. They wanted something closer to a working partner: a tool that could help them think through the right recommendation, compare alternatives and explain the proposal with confidence.\n\nThe research helped define a set of principles that guided the interface: make the system's logic visible; design for field work, not desk work; treat comparison as the core action; use AI to explain and validate, not to hide complexity; reduce uncertainty at the moments where advisors make decisions.\n\nThe AI layer was designed to appear where it could actually help. Recommendation cards appeared during plan selection. Validation alerts appeared when a configuration was incomplete or risky. Conversational input worked as a shortcut for advisors who already knew what they wanted. AI was not treated as a separate section of the product. It was part of the quotation process itself.\n\nWe validated the prototype in Gesell room sessions with real advisors. This confirmed that the new direction felt modern and clear, but also showed where the design needed more warmth, better hierarchy and simpler information architecture.`,
      es: `Primero trabajamos desde investigación. Más que preguntar qué querían los asesores, buscamos entender cómo vendían realmente: qué hacían cuando el sistema fallaba, cómo usaban Excel, qué información revisaban dos veces y en qué momentos perdían confianza.\n\nDe ahí salieron principios de diseño que guiaron el producto:\n\nMostrar la lógica del sistema.\nDiseñar para trabajo en campo.\nHacer de la comparación la acción principal.\nUsar IA para explicar y validar, no para esconder complejidad.\nReducir incertidumbre en los momentos de decisión.\n\nDespués estructuré la experiencia en capas.\n\nLa primera era el flujo base de cotización. La segunda era la capa de IA, con recomendaciones, alertas y atajos conversacionales. La tercera era una vista previa en tiempo real del documento final, porque los asesores necesitaban confirmar que lo que configuraban era exactamente lo que el cliente recibiría.\n\nProbamos el prototipo con asesores reales. La validación ayudó a ajustar jerarquías, simplificar secciones colapsables y hacer que la interfaz se sintiera menos fría sin perder precisión.`,
    },
    keyDecisions: {
      en: `AI recommendations as reasoning cards. The original expectation was closer to the system telling the advisor the right plan. I pushed the design toward recommendation cards that explain the logic behind each suggestion. The advisor sees why a plan is recommended, what client variables were considered and where there may be uncertainty. The AI supports the decision, but does not own it. In a financial sales context, trust is more valuable than speed alone.\n\nConversational input as a shortcut, not the main flow. Conversational quoting was one of the most visible ideas, but I did not position it as the primary way to use the tool. For many advisors, structured fields gave more control and reduced the risk of mistakes. The conversational assistant worked better as an accelerator for experienced users. The design needed to work for different levels of digital confidence, not just for the most advanced users.\n\nReal-time preview as a trust signal. The proposal preview was a direct response to a trust problem. If advisors could see the client-facing output update as they configured the quotation, they no longer had to wonder whether the system would generate something different at the end. Reducing that uncertainty was part of rebuilding adoption.`,
      es: `La IA como herramienta de asistencia y recomendación.\nDiseñé las recomendaciones como tarjetas con razonamiento. La idea era mostrar por qué el sistema sugería cierto plan y qué variables estaba considerando. El asesor podía decidir con más contexto, sin sentir que la herramienta le estaba quitando control.\n\nEl input conversacional como atajo, no como flujo principal.\nAunque la cotización conversacional era una de las funciones más atractivas, no la traté como el camino principal. Para muchos asesores, los campos estructurados daban más precisión. El chat funcionaba mejor como acelerador para quien ya sabía lo que quería.\n\nLa vista previa como señal de confianza.\nLa propuesta en tiempo real ayudaba a resolver una ansiedad muy concreta: "¿el documento final va a coincidir con lo que configuré?". Esa visibilidad reducía dudas y hacía que el sistema se sintiera más confiable.`,
    },
    outcome: {
      en: `The redesigned experience changed how advisors perceived the tool. NPS moved from −6.7% to 66.7%, a 73-point swing. The prototype reached a 90.2 SUS score. One hundred percent of advisors in the validation cohort said they would recommend the tool to colleagues.\n\nAI recommendations became one of the strongest proof points because they were useful without feeling like a black box. The interaction patterns created for this tool started to influence other internal product experiences at the same company.`,
      es: `La nueva experiencia cambió la percepción de la herramienta.\n\nEl NPS pasó de −6.7% a 66.7%. El SUS alcanzó 90.2. El 100% de los asesores en la validación dijo que recomendaría la herramienta a colegas.\n\nMás allá de las métricas, el cambio importante fue que la herramienta empezó a sentirse como un apoyo real para la venta, en lugar de un formulario que había que completar.\n\nLas recomendaciones de IA funcionaron porque respetaban el criterio del asesor. La comparación en tiempo real ayudó a tomar mejores decisiones. La vista previa redujo dudas sobre el resultado final.`,
    },
    learned: {
      en: `The biggest lesson was that the most important design decisions happened before the screens looked finished. The research, the behavioral mapping and the way we translated advisor needs into product principles were what made the interface credible. The UI was the visible layer, but the real work was deciding what the product needed to make explicit, what it needed to simplify and where AI actually created value.\n\nThis project also reinforced how I think about AI in enterprise tools. AI works better when it respects the user's expertise. Once the product says here is what I see, here is why, you decide. The experience becomes more useful and easier to trust.\n\nAI that does not know its limits becomes a liability. We designed the AI layer to be visibly confident only when the data supported it. When it was not sure, it got out of the way. That restraint was harder to get right than any feature we shipped.`,
      es: `Este proyecto reforzó algo que aparece mucho en mi forma de diseñar: el impacto más importante ocurre antes de abrir Figma.\n\nLa investigación, el entendimiento del comportamiento y la definición de principios fueron los que hicieron que la interfaz tuviera sentido. La UI era la parte visible, pero la decisión de diseño estaba en cómo reconstruir confianza dentro de un proceso complejo.\n\nTambién me dejó una postura más clara sobre IA en productos enterprise. La IA es más útil cuando asesora sin imponer. Funciona cuando muestra lo que ve, explica por qué lo sugiere y deja que la persona decida.`,
    },
    metrics: [
      { value: '66.7%', label: { en: 'NPS (from −6.7%)', es: 'NPS (desde −6.7%)' } },
      { value: '90.2',  label: { en: 'SUS score',         es: 'SUS score' } },
      { value: '100%',  label: { en: 'advisor rec. rate', es: 'recomendación asesores' } },
    ],
    tags: ['AI Product Design', 'Discovery', 'UX Research', 'Enterprise UX', 'Interaction Architecture', 'Conversational AI'],
    imageBg: 'from-indigo-900 to-blue-800',
    images: {
      hero: [
        '/images/projects/quoting-rewired/01-hero-01.webp',
        '/images/projects/quoting-rewired/01-hero-02.webp',
        '/images/projects/quoting-rewired/01-hero-03.webp',
      ],
      processMap: '/images/projects/quoting-rewired/02-process-map.webp',
      artifacts:  '/images/projects/quoting-rewired/03-evidence-artifacts.webp',
      impact:     '/images/projects/quoting-rewired/04-impact-metrics.webp',
    },
  },
  {
    id: 'one-system',
    slug: 'one-system',
    number: '02',
    isLab: false,
    industry: { en: 'Telecom & Entertainment', es: 'Telecom & Entretenimiento' },
    year: '2022–2023',
    role: { en: 'Design System Lead · UX/UI', es: 'Lead Design System · UX/UI' },
    confidentiality: { en: 'Public-friendly', es: 'Versión pública' },
    title: { en: 'One system for a whole ecosystem.', es: 'Un sistema para un ecosistema.' },
    subtitle: { en: 'Design system and digital transformation across web, mobile, and TV.', es: 'Design system y transformación digital para web, móvil y TV.' },
    hook: { en: 'How do you create one system without flattening a whole ecosystem?', es: '¿Cómo creas un sistema sin aplanar todo un ecosistema?' },
    overview: {
      en: `This project was about turning a fragmented digital ecosystem into one coherent product language.\n\nThe company had web, mobile and TV experiences that had grown separately. Each platform had its own patterns, rules and visual decisions. At the same time, the business was trying to evolve beyond traditional telecom services and become a broader digital ecosystem with entertainment, delivery, loyalty and financial services.\n\nI led the design system work across that transformation. The goal was not just to make the screens look consistent. The real challenge was creating a system that could absorb a changing brand, support different interaction models and help several product teams move in the same direction.\n\nThe work also extended beyond the screen. The TV experience depended on a physical remote control, so the system had to connect digital interface decisions with hardware, accessibility and real living-room behavior.`,
      es: `Este proyecto consistió en convertir un ecosistema fragmentado en un lenguaje de producto coherente.\n\nLa compañía tenía experiencias web, mobile y TV que habían crecido por separado. Cada plataforma tenía sus propias reglas, componentes y decisiones visuales. Al mismo tiempo, el negocio estaba evolucionando hacia una experiencia digital más amplia, con entretenimiento, servicios, loyalty, ecommerce y productos financieros.\n\nLideré el trabajo de design system para unificar ese ecosistema. El reto era crear una estructura suficientemente flexible para soportar distintas plataformas, una marca en evolución y equipos con formas de trabajo distintas.\n\nEl sistema terminó conectando tres plataformas digitales y una capa física: el control remoto de TV, que también se rediseñó con señales táctiles y braille.`,
    },
    context: {
      en: `The company was moving from a traditional telecom model into a larger digital ecosystem. That meant the product experience had to support much more than connectivity: entertainment, ecommerce, loyalty, digital services and customer support.\n\nThe problem was that the experience had been built by different teams at different times. Web, mobile and TV had different visual standards, different components and different interaction rules. Even basic actions could look and behave differently depending on the platform.\n\nIn parallel, the brand was also evolving. The new direction was more futuristic and technology-forward, with a stronger visual personality. That created another layer of complexity: the design system had to support change while the change was still happening.\n\nThis was the core tension of the project: build something stable enough for product and engineering, but flexible enough for a brand and business model in motion.`,
      es: `La compañía venía de un modelo tradicional de telecomunicaciones. Su negocio original estaba alrededor de internet, telefonía y TV, pero el mercado ya exigía algo más amplio: servicios digitales, entretenimiento, beneficios, compras y experiencias integradas.\n\nEl problema era que cada plataforma había avanzado por su cuenta. Web, app móvil y TV tenían diferentes estándares visuales, distintos patrones de interacción y poca gobernanza compartida.\n\nEn paralelo, la marca estaba cambiando hacia una dirección más tecnológica y futurista. Eso agregaba otra capa de complejidad: el design system tenía que dar estabilidad mientras la identidad visual seguía en movimiento.\n\nAdemás, la experiencia no terminaba en la pantalla. En TV, el control remoto era la forma principal de interacción para millones de personas. Si ese objeto no acompañaba la nueva experiencia, el sistema quedaba incompleto.`,
    },
    myRole: {
      en: `I led the design system architecture and helped translate the new brand direction into usable product decisions.\n\nMy work included defining the structure of the system: tokens, components, patterns and documentation, and creating UI standards that could work across web, mobile and TV without forcing every platform into the same mold. I translated brand decisions into scalable interface rules: color tokens, typography scales, spacing, states, motion principles and component behavior. I designed reusable patterns for telecom services, entertainment, ecommerce, loyalty, financial products and support flows.\n\nI also supported the 10ft UI, where navigation, focus states and content density follow completely different rules from web or mobile, and participated in the redesign of the physical remote control, including tactile differentiation and Braille signals on key buttons. My work connected product, UX, engineering, research and creative teams across countries.\n\nMy responsibility was to keep the system usable for designers, understandable for engineers and useful for the business.`,
      es: `Lideré la arquitectura del design system y su evolución entre plataformas.\n\nMi trabajo incluyó definir tokens, componentes, patrones, documentación y reglas de uso para equipos de producto e ingeniería. También ayudé a traducir la nueva dirección de marca en decisiones de interfaz que pudieran escalar, en lugar de quedarse como exploraciones visuales aisladas.\n\nTrabajé en componentes y patrones para web, mobile y TV, considerando que cada plataforma tiene un modelo de interacción distinto.\n\nTambién participé en el rediseño del control remoto físico, especialmente en decisiones de distribución, diferenciación táctil y accesibilidad.\n\nMi rol era mantener una tensión sana: suficiente consistencia para que el ecosistema se sintiera unido y suficiente flexibilidad para que cada plataforma funcionara bien en su contexto.`,
    },
    whatMadeItInteresting: {
      en: `A website, a mobile app and a TV interface do not behave the same way. Web can handle dense layouts and hover states. Mobile depends on touch, thumb reach and limited space. TV is navigated with a remote control from several meters away, which makes focus states, reading distance and directional navigation critical. A single system could not mean one component copied everywhere. It needed shared logic with platform-specific behavior.\n\nThe brand was changing while the system was being built. A design system is often created after the brand is clear. Here, both things were moving at the same time. That made tokens essential: if color, spacing, typography and visual treatments were defined as reusable decisions, the system could adapt without redesigning every component from zero.\n\nThe product experience had a physical layer. The TV remote was not a secondary object. For many subscribers, it was the main way to interact with the ecosystem. Improving the TV interface without improving the remote would have left part of the experience unresolved. This forced the system to cross the edge of the screen.\n\nAdoption was an organizational problem. Some teams had never used a design system before. Others had their own ways of working. A good library was not enough. The system needed governance, documentation and practical support so teams could adopt it because it helped them, not because someone told them to.`,
      es: `Lo más interesante era que el sistema no podía ser una librería genérica.\n\nWeb, mobile y TV no se usan igual. En web hay cursor, hover y más densidad. En mobile hay tacto, tamaño de pantalla y gestos. En TV hay distancia, foco, navegación direccional y un control remoto como entrada principal.\n\nEso obligaba a separar el significado de los componentes de su representación visual. Una card podía ser parte del mismo sistema, pero no comportarse igual en una pantalla táctil que en una TV vista desde tres metros.\n\nTambién estaba la marca en movimiento. El sistema tenía que absorber cambios sin romper lo que ya se estaba construyendo.\n\nY el control remoto hacía el proyecto más completo. Era una prueba clara de que un design system puede extenderse más allá de la pantalla.`,
    },
    howIApproached: {
      en: `The work started with an audit: mapping inconsistencies across platforms. The same actions, components and flows appeared with different rules depending on where the user was. This audit made the fragmentation visible and gave the team a concrete reason to invest in a system rather than continue fixing screens one by one.\n\nI structured the system in three layers. Tokens: base values covering color, typography, spacing, radius, shadows and other reusable decisions. Components: buttons, cards, inputs, modals, navigation and other interface elements with platform-specific variants. Patterns: recurring flows and behaviors, like onboarding, checkout, plan management, content browsing and support interactions. This structure mattered because the business was not designing one product. It was building an ecosystem.\n\nFor TV, I created a 10ft adaptation logic: same design language, but different rendering rules. Typography needed to scale differently. Cards needed clearer focus states. Layouts needed predictable directional navigation. Content density had to drop because the user was not sitting close to the screen. The key was separating the meaning of a component from its platform expression.\n\nThe remote control became one of the clearest examples of the project's logic. We worked on button layout, tactile differentiation and Braille signals on key buttons, helping users navigate by touch, in low-light environments and with different levels of visual ability. Accessibility was designed into the default product, not treated as a separate version.`,
      es: `Empezamos con una auditoría para mapear inconsistencias. La misma acción podía tener distintos estilos, componentes y comportamientos dependiendo de la plataforma. Eso hizo visible el costo de seguir trabajando sin una fuente de verdad.\n\nDespués estructuré el sistema en tres capas:\n\nTokens.\nColor, tipografía, espaciado, radios, sombras y valores base. Esta capa era clave porque la marca estaba cambiando y necesitábamos que el sistema pudiera adaptarse.\n\nComponentes.\nBotones, cards, inputs, navegación, modales y otros elementos reutilizables. Cada componente podía tener variantes por plataforma sin romper el lenguaje compartido.\n\nPatrones.\nFlujos y comportamientos recurrentes: onboarding, checkout, gestión de servicios, exploración de contenido y soporte.\n\nPara TV, trabajé una capa específica de adaptación 10ft. La experiencia necesitaba foco claro, navegación predecible, tipografía más grande y menor densidad de información.\n\nEn paralelo, acompañé la adopción del sistema con guías, sesiones con equipos y revisión de implementación. Había que ayudar a que el sistema se usara bien y la documentación era fundamental para lograrlo.`,
    },
    keyDecisions: {
      en: `Tokens before components. It would have been faster to start by building buttons and cards. I pushed for tokens first because the brand was still changing. That made early progress less visible, but it saved rework later. When a foundational brand value changed, the system could update from the base instead of manually fixing every screen. A system needs to survive change, not freeze a moment in time.\n\nOne system with platform variants. The easier route would have been to create three separate systems with similar principles. I chose one shared system with platform-specific behavior. That created more complexity upfront, but it made long-term consistency and maintenance much stronger. The user should feel one ecosystem, even when each platform behaves differently.\n\nAccessibility as part of the default product. Braille signals and tactile textures were not part of the original brief. They emerged from thinking seriously about who uses the remote and how. Instead of treating accessibility as a special edition, we integrated it into the main product. Inclusive design is stronger when it improves the core experience for everyone.\n\nCoaching adoption instead of forcing it. A design system can fail if it becomes a document that nobody wants to use. I focused on making adoption practical: usage guides, reviews, syncs with engineering and support for teams that were new to this way of working. A system only creates value when teams actually build with it.`,
      es: `Empezar por tokens antes que por componentes.\nEra tentador construir botones y cards desde el inicio porque se ve más tangible. Pero la marca seguía cambiando, así que necesitábamos primero una base que pudiera absorber esos cambios. Eso redujo retrabajo después.\n\nUn sistema con variantes, no tres sistemas separados.\nHacer sistemas separados para web, mobile y TV habría sido más fácil al principio, pero más difícil de mantener. La decisión fue construir un sistema compartido con reglas específicas por plataforma.\n\nAccesibilidad integrada en el producto base.\nEl braille y las texturas táctiles del control remoto no debían vivir como una versión especial. La accesibilidad tenía que estar dentro del producto principal.\n\nAcompañar la adopción, no imponerla.\nVarios equipos no tenían experiencia trabajando con design systems. En lugar de forzar la adopción desde gobernanza, el enfoque fue demostrar valor práctico: ahorrar tiempo, reducir ambigüedad y mejorar calidad de implementación.`,
    },
    outcome: {
      en: `The design system became the foundation for a broader digital and physical transformation. With 12M+ subscribers served, the app reached 5M+ downloads and ranked #12 in entertainment downloads nationally. Web, mobile and TV experiences were unified under one system. The physical remote control was redesigned as an extension of the same experience principles.\n\nProduct teams adopted shared components, patterns and documentation. Brand evolution could land across digital touchpoints faster because it was built into the system architecture. Accessibility decisions, including Braille signals and tactile textures, shipped in the default remote control. Teams across Mexico, the US and Portugal worked from a more aligned design language.`,
      es: `El design system se volvió una base para la transformación digital y física de la compañía.\n\nLa experiencia unificada acompañó una app con 5M+ descargas y posicionamiento nacional en entretenimiento. El sistema conectó web, mobile y TV bajo un mismo lenguaje de diseño, con el control remoto como una extensión física de esos principios.\n\nLa marca pudo aterrizar de forma más consistente en distintos touchpoints. Los equipos empezaron a trabajar con componentes, patrones y documentación compartida. El control remoto integró señales táctiles y braille para mejorar accesibilidad desde el producto base.\n\nEl resultado más importante fue que el sistema permitió coordinar producto, marca, ingeniería y hardware desde una misma lógica.`,
    },
    learned: {
      en: `This project changed how I think about design systems. A design system is not mainly about making things look consistent. Its bigger value is helping a product ecosystem absorb change. Brands evolve. Platforms appear. Business models shift. Teams rotate. The system has to create enough structure so the product can keep moving without becoming fragmented again.\n\nIt also reinforced that digital experience does not end at the screen. In this project, the remote control was as important as the interface because it shaped how millions of people accessed the product. That physical layer made the system more real.\n\nFor me, the strongest design systems are not libraries. They are shared languages: built for teams, platforms and decisions. The governance model, the documentation, the contribution process: those are what determine whether the system survives beyond the people who built it.`,
      es: `Este proyecto cambió mi forma de entender los design systems.\n\nUn buen sistema más que existir para que todo se vea consistente debe ayudar a que sus productos absorban cambios ya sea de marcas, equipos o plataformas completas.\n\nTambién reforzó algo que me interesa mucho: el diseño digital no termina en la interfaz. En este caso, el control remoto era tan importante como la pantalla porque definía cómo muchas personas realmente usaban el producto.\n\nPara mí, un design system exitoso es un sistema con lenguaje compartido que ayuda a tomar mejores decisiones en escala.`,
    },
    metrics: [
      { value: '12M+', label: { en: 'subscribers',       es: 'suscriptores' } },
      { value: '5M+',  label: { en: 'app downloads',     es: 'descargas de la app' } },
      { value: '#12',  label: { en: 'entertainment rank', es: 'ranking entretenimiento' } },
    ],
    tags: ['Design System', 'Design Ops', 'Multi-platform UX', 'Digital Transformation', 'Accessibility', 'Hardware Design'],
    imageBg: 'from-purple-900 to-indigo-800',
    images: {
      hero: [
        '/images/projects/one-system-for-a-whole-ecosystem/01-hero-01.webp',
        '/images/projects/one-system-for-a-whole-ecosystem/01-hero-02.webp',
        '/images/projects/one-system-for-a-whole-ecosystem/01-hero-03.webp',
      ],
      processMap: '/images/projects/one-system-for-a-whole-ecosystem/02-process-map.webp',
      artifacts:  '/images/projects/one-system-for-a-whole-ecosystem/03-artifact-detail.webp',
      impact:     '/images/projects/one-system-for-a-whole-ecosystem/04-impact-chart.webp',
    },
  },
  {
    id: 'behavior-meets-funnel',
    slug: 'behavior-meets-funnel',
    number: '03',
    isLab: false,
    industry: { en: 'Telecom', es: 'Telecom' },
    year: '2024–2025',
    role: { en: 'UX Lead · CRO & Qualitative Research', es: 'UX Lead · CRO & Investigación Cualitativa' },
    confidentiality: { en: 'Anonymized (NDA)', es: 'Anonimizado (NDA)' },
    title: { en: 'Where behavior meets the funnel.', es: 'Donde el comportamiento se encuentra con el funnel.' },
    subtitle: { en: 'CRO and behavioral design for a telecom acquisition flow.', es: 'CRO y behavioral design para un flujo de adquisición telco.' },
    hook: { en: 'What has to become clearer for users to keep moving?', es: '¿Qué tiene que volverse más claro para que los usuarios sigan avanzando?' },
    overview: {
      en: `This project was about adding the missing "why" to a CRO program.\n\nThe team already had analytics. They knew where users dropped off, which pages underperformed and which experiments moved a metric. What was missing was a clearer understanding of the behavior behind those numbers.\n\nI led the qualitative research and behavioral design layer across several telecom markets in the Caribbean and Central America. The work included usability testing, UX audits, heatmap analysis, empathy maps, benchmarks and experiment briefs designed to connect user behavior with business decisions.\n\nThe shift was important: instead of testing changes based mainly on assumptions, the team started building experiments from observed friction, user intent and market-specific context.`,
      es: `Este proyecto consistió en sumar la capa cualitativa que le faltaba a un programa de CRO.\n\nEl equipo ya tenía datos. Sabía dónde caían los usuarios, qué páginas tenían menor desempeño y qué experimentos movían alguna métrica. Lo que faltaba era entender por qué estaba pasando.\n\nLideré investigación cualitativa y diseño conductual para varios mercados de telecomunicaciones en Caribe y Centroamérica. El trabajo incluyó pruebas de usabilidad, análisis de heatmaps, auditorías UX, empathy maps, benchmarks y briefs de experimentos conectados con hallazgos reales.\n\nLa intención era cambiar la forma de experimentar: dejar de probar cambios basados en intuición visual y empezar a diseñar hipótesis desde comportamiento observado.`,
    },
    context: {
      en: `The client operates across multiple Caribbean and Central American markets, with digital acquisition flows for internet, mobile, TV and landline services. Their CRO program had already been running for some time. The team was testing landing pages, forms, cards, calls to action and chatbot flows. Some experiments worked. Many produced mixed results.\n\nThe problem was not the lack of data. The problem was that data was being used mostly to locate friction, not to explain it. A funnel chart could show that users abandoned a step. It could not explain whether they were confused, comparing options, looking for reassurance, trying to contact a human or simply expecting the page to behave differently.\n\nThat was the space where qualitative research became useful.`,
      es: `El cliente operaba servicios de internet, móvil, TV y telefonía en varios mercados. Su equipo digital llevaba tiempo haciendo CRO con A/B tests, ajustes en landing pages, formularios, CTAs y flujos de adquisición.\n\nEl problema era que los resultados eran inconsistentes. Algunos experimentos funcionaban, otros no, y muchas veces no quedaba claro por qué.\n\nLa analítica mostraba el "qué": abandono, rage clicks, bajo avance en funnel, poco engagement o caída en ciertos pasos. Pero faltaba una forma más sistemática de entender el comportamiento detrás de esos datos.\n\nAhí entró la investigación cualitativa, integrada al negocio como una forma de construir mejores experimentos.`,
    },
    myRole: {
      en: `I led the qualitative and behavioral layer of the CRO program. My work included planning and synthesizing usability tests across markets; reviewing real user sessions through heatmaps and recordings; building empathy maps and user profiles for relevant segments, including users between 40 and 55 years old; and translating findings into experiment briefs for the CRO team.\n\nI ran UX audits on critical flows such as checkout, plan comparison and device browsing, and worked on chatbot flows through conversational design and behavioral insights. My work connected research findings with advertising, content and local market teams across the region.\n\nMy job was to make user behavior visible enough for the business to act on it.`,
      es: `Lideré la capa de investigación cualitativa y diseño conductual dentro del programa de CRO.\n\nMi trabajo incluyó planear y sintetizar pruebas de usabilidad, revisar grabaciones y heatmaps, construir empathy maps, identificar patrones por mercado y traducir hallazgos en briefs de experimentos.\n\nTambién trabajé en flujos de chatbot desde conversational design, conectando tono, estructura, CTAs y fricciones con oportunidades de conversión.\n\nLa responsabilidad principal era hacer visible el comportamiento del usuario para que el equipo pudiera tomar decisiones más precisas: explicar el comportamiento detrás de cada caída en el funnel.`,
    },
    whatMadeItInteresting: {
      en: `The same digital ecosystem served several countries, but users did not behave the same way everywhere. Some markets were more comfortable completing a purchase online. Others used the website to compare and then moved to phone, chat or physical stores. Trust signals, device preferences and expectations around support also changed by market. We could not treat the region as one generic user base.\n\nThe organization trusted numbers more than observation. The team was used to quantitative evidence. Introducing qualitative research required showing that a usability test, a heatmap pattern or a repeated quote could reveal something that analytics alone could not. This was partly a methodology challenge and partly a storytelling challenge.\n\nThe funnel was not fully digital. Users did not always abandon because the website failed. Sometimes they left because they wanted human confirmation, needed to check coverage, preferred a store or did not trust the information enough to continue. For CRO, that distinction matters. A channel switch is not always a failure. Sometimes it is the user choosing the path that feels safer.`,
      es: `Lo interesante era que el problema era la falta de interpretación de los datos recopilados.\n\nEl equipo tenía dashboards, métricas y reportes. Pero muchas decisiones seguían basadas en suposiciones: cambiar un botón, mover una sección, reducir texto, ajustar un formulario.\n\nEl comportamiento real mostraba cosas más específicas. Usuarios que hacían clic donde no había interacción. Personas que usaban la búsqueda como filtro. Clientes que salían del sitio porque el canal digital no les daba suficiente seguridad para cerrar ahí.\n\nTambién era un reto porque cada mercado se comportaba distinto. No podíamos asumir que una solución regional aplicaba igual para todos los países.`,
    },
    howIApproached: {
      en: `We used a mix of methods depending on the experiment and market: usability testing with task-based sessions to observe how users moved through acquisition flows; heatmap analysis to identify rage clicks, dead zones, scroll behavior and abandoned paths; structured UX audits of key flows against usability and telecom best practices; benchmarking against regional and global telecom experiences; and emerging methods like interviews and feedback surveys when needed.\n\nA recurring pattern was that analytics could show a problem, but users revealed the reason. A plan card might show low click-through. A heatmap could reveal rage clicks on the card body. A usability session could confirm that users expected the whole card to be clickable, not just the small CTA. That changes the experiment. The question stops being "should we change the button color?" and becomes "does the interaction match what the visual design is promising?"\n\nI used empathy maps to help teams see the person behind the conversion issue. For teams used to performance dashboards, empathy maps created a more human entry point into the problem. Each experiment brief connected qualitative evidence with CRO execution: observed behavior → behavioral hypothesis → design intervention → expected measurable outcome.`,
      es: `El enfoque fue conectar métodos cualitativos con decisiones de experimentación.\n\nUsamos pruebas de usabilidad para observar tareas concretas. Revisamos heatmaps para detectar rage clicks, scroll innecesario, zonas muertas y patrones de abandono. Hicimos auditorías UX en flujos críticos como checkout, comparación de planes y tienda de dispositivos. Complementamos con benchmarks y otros métodos cuando el contexto lo pedía.\n\nDespués convertimos esos hallazgos en una estructura simple para los experimentos:\n\nComportamiento observado.\nHipótesis conductual.\nIntervención de diseño.\nResultado medible esperado.\n\nEsto ayudó a que la investigación no se quedara como un reporte bonito. Cada insight tenía que poder convertirse en una prueba.`,
    },
    keyDecisions: {
      en: `Start with behavior, then show the metric. When presenting findings, I avoided opening only with dashboards. I started with what users were doing, saying and trying to solve. That helped the team understand that conversion problems are often behavior problems before they are interface problems. It made qualitative research feel practical, not anecdotal.\n\nSeparate market-specific insights from regional patterns. Each market needed its own interpretation. At the same time, some behaviors repeated across countries, like rage clicks on cards or confusion around navigation. I made a clear distinction between local findings and cross-market patterns so the team could act with both precision and scale. Regional leverage should not erase local behavior.\n\nTreat channel switching honestly. If users left digital for phone, chat or store, I did not frame that automatically as failure. Sometimes the website had to support the handoff better instead of pretending every user should complete everything online. A better conversion strategy can include better transitions between channels.`,
      es: `Partir del comportamiento antes que de la métrica.\nEn lugar de presentar solo números, usé empathy maps y ejemplos observados para mostrar qué estaba viviendo la persona usuaria. Eso ayudó a que el equipo entendiera la fricción desde el punto de vista del usuario, no solo desde el dashboard.\n\nSeparar insights locales de patrones regionales.\nCada mercado necesitaba su lectura propia, pero algunos patrones se repetían. Hice esa separación para que el equipo pudiera actuar con precisión sin perder escala.\n\nDiseñar handoffs, no fingir que todo debía cerrar en digital.\nAlgunos usuarios preferían teléfono, chat o tienda física en ciertos momentos. En lugar de verlo automáticamente como fracaso del funnel, lo abordé como una oportunidad para diseñar mejores transiciones entre canales.\n\nConvertir hallazgos en briefs accionables.\nCada recomendación debía poder probarse. Eso hizo que la investigación se sintiera útil para CRO, no como una capa externa o demasiado abstracta.`,
    },
    outcome: {
      en: `The program helped the organization evolve how it thought about CRO. Experiments became more connected to observed user behavior. Qualitative research started informing the experimentation pipeline, not just explaining results after the fact. The team adopted a more hybrid prioritization model combining analytics, usability findings, heatmaps and market context.\n\nA research repository in Jira reduced duplicated work and made findings easier to reuse. The 40–55 segment became more actionable for digital and physical channel planning. Advertising, content and local market teams began using qualitative evidence in their own decisions across Caribbean and Central American markets.`,
      es: `El programa evolucionó conectando el comportamiento real de los usuarios (cualitativo) con los datos obtenidos desde el análisis (cuantitativo).\n\nSe realizaron 15+ pruebas de usabilidad en distintos mercados, 4 auditorías UX y múltiples briefs de experimentos por sprint. Los hallazgos ayudaron a priorizar intervenciones como navegación persistente, cards completamente clickeables, search-as-filter en tienda de dispositivos y mejoras en flujos conversacionales.\n\nTambién se creó una base de conocimiento en Jira para reducir investigación duplicada y hacer más reutilizables los aprendizajes entre mercados.\n\nEl mayor resultado fue metodológico: el equipo empezó a construir experimentos desde evidencia cualitativa y cuantitativa, no solo desde métricas aisladas.`,
    },
    learned: {
      en: `This project reinforced that CRO is not just about optimizing screens. It is about understanding why people hesitate, compare, misclick, leave, return or ask for help. Analytics gives the signal. Behavioral research gives the explanation. The value comes from connecting both in a way the business can test.\n\nIt also reminded me that the hardest part is often not finding the insight. It is making the method credible for a team that is used to numbers. Once stakeholders see that a single observed behavior can explain a repeated pattern in the data, the conversation changes. The team stops asking "what do we test next?" and starts asking "what do users need to be able to decide?"\n\nWorking across different markets also made me more careful about regional assumptions. The same product can create very different experiences depending on who is using it, what they trust and how digital they expect the process to be. That context does not show up in conversion data alone.`,
      es: `Este proyecto reforzó que CRO no se trata solo de optimizar pantallas. Se trata de entender comportamiento.\n\nUna métrica localiza el problema. La investigación explica por qué ocurre: si la persona está dudando, comparando, buscando seguridad, esperando otra interacción o intentando cambiar de canal.\n\nTambién me dejó claro que vender el método puede ser tan importante como vender el insight. Para un equipo acostumbrado a números, la investigación cualitativa necesita demostrar valor rápido. Cuando un comportamiento observado explica un patrón repetido en datos, la conversación cambia.`,
    },
    metrics: [
      { value: '15+',     label: { en: 'usability tests',        es: 'pruebas de usabilidad' } },
      { value: '4',       label: { en: 'UX audits',              es: 'auditorías de UX' } },
      { value: '3/sprint', label: { en: 'experiments per sprint', es: 'experimentos por sprint' } },
    ],
    tags: ['CRO', 'Behavioral Design', 'Usability Testing', 'Heatmap Analysis', 'UX Research', 'Conversational Design'],
    imageBg: 'from-teal-900 to-cyan-800',
    images: {
      hero: [
        '/images/projects/where-behavior-meets-the-funnel/01-hero.webp',
        '/images/projects/where-behavior-meets-the-funnel/01-hero-02.webp',
      ],
      processMap: '/images/projects/where-behavior-meets-the-funnel/02-process-map.webp',
      artifacts:  '/images/projects/where-behavior-meets-the-funnel/03-artifact-detail.webp',
      impact:     '/images/projects/where-behavior-meets-the-funnel/04-impact-chart.webp',
    },
  },
  {
    id: 'xolodrilo',
    slug: 'xolodrilo',
    number: '04',
    isLab: true,
    industry: { en: 'Side Project / Lab', es: 'Proyecto Personal / Lab' },
    year: '2025',
    role: { en: 'Designer & AI Director', es: 'Designer & AI Director' },
    confidentiality: { en: 'Public', es: 'Público' },
    title: { en: 'Xolodrilo: designing a game with AI.', es: 'Xolodrilo: diseñando un juego con IA.' },
    subtitle: { en: 'AI-assisted case study: characters, mechanics, and visual system built with vibe coding.', es: 'Caso de estudio AI-assisted: personajes, mecánicas y sistema visual construido con vibe coding.' },
    hook: { en: 'How far can AI take a game idea before product judgment has to take over?', es: '¿Hasta dónde puede la IA llevar una idea de juego antes de que el criterio de producto tome el control?' },
    overview: {
      en: `Xolodrilo started as a small educational game request and became a way to test how far I could push AI-assisted design without lowering the craft bar.\n\nThe goal was to create a playable 2D platformer with a Mexican cultural and environmental theme. It needed to work in a classroom context, run on different devices and feel finished enough to be presented publicly.\n\nI designed and built the full product in six weeks: characters, visual system, mechanics, sound, responsive experience and deployment. AI tools helped accelerate production, but I directed, edited and refined every important output.\n\nThe result was a playable game for web, mobile and Smart TV. It won a regional school prize and later became an example used in high schools to show how AI can support creative production.`,
      es: `Xolodrilo empezó como un proyecto escolar y terminó siendo un laboratorio real para probar diseño asistido por IA.\n\nLa idea era crear un platformer 2D con tema mexicano y conciencia ambiental. Tenía que ser jugable, funcionar en contexto de salón de clases y sentirse suficientemente pulido para presentarse públicamente.\n\nDiseñé y construí el producto completo en seis semanas: personajes, sistema visual, mecánicas, sonido, experiencia responsive y despliegue. Usé IA para acelerar la producción, pero mantuve dirección creativa y criterio de diseño en cada decisión importante.\n\nEl resultado fue un juego jugable para web, mobile y Smart TV, con 47 sprites, 18 archivos de audio, 12 fondos y alrededor de 8,500 líneas de código. Ganó un premio regional escolar y después fue usado como ejemplo educativo de creación asistida por IA.`,
    },
    context: {
      en: `The initial ask was simple: create an educational game for a school project. It needed to connect with Mexican culture, include an environmental awareness message and be playable in a classroom setting. I could have delivered a basic prototype. Instead, I used it as a personal lab.\n\nAt the time, I was already thinking a lot about AI in product design. In enterprise work, AI usually appears as a feature inside the experience: a recommendation engine, a chatbot, a validation layer. Here, I wanted to explore something different: AI as part of the production process itself.\n\nThe question was practical: can AI help create a real, playable product faster while still keeping taste, direction and quality under human control?`,
      es: `El pedido inicial era simple: alguien cercano necesitaba un juego educativo para un proyecto escolar. Tenía que tener una temática cultural mexicana, un mensaje ambiental y ser fácil de presentar en un salón de clases.\n\nPude haber hecho un prototipo básico, pero decidí usarlo como una prueba más ambiciosa.\n\nQuería explorar si la IA podía acelerar un proceso creativo completo sin que el resultado se sintiera genérico o poco cuidado, como producto real, con usuarios, deadline y restricciones de plataforma.\n\nLa pregunta que guiaba el proyecto era muy práctica: ¿qué tanto puede avanzar un diseñador cuando usa IA como capa de producción, sin soltar el control creativo?`,
    },
    myRole: {
      en: `I worked as designer, AI director and developer simultaneously. That meant I was responsible for defining the concept, characters and visual direction; designing the game mechanics and overall UX; directing AI-generated assets and deciding what was usable, what needed editing and what should be discarded; and refining sprites, backgrounds and visual details manually.\n\nI also built the game with React, Phaser and TypeScript through vibe coding, solved cross-platform behavior for desktop, mobile and Smart TV, created audio direction with sound effects and music loops, and deployed and tested the final experience.\n\nAI helped with speed. I stayed responsible for every decision.`,
      es: `Fui diseñador, director de IA y desarrollador del proyecto.\n\nDefiní el concepto, personajes, dirección visual, mecánicas, audio, arquitectura del juego, experiencia multi-plataforma y despliegue.\n\nUsé herramientas de IA para generar material base: personajes, animaciones, fondos, texturas y audio. Después edité, limpié y refiné manualmente los assets para que funcionaran como parte de un mismo sistema visual.\n\nTambién construí el juego con React, Phaser y TypeScript mediante vibe coding, manteniendo control sobre estructura, escenas, entidades, controles, estados y fallback offline.`,
    },
    whatMadeItInteresting: {
      en: `The game needed original characters with a Mexican fauna base and a contamination-inspired mutant layer. Three characters shipped: Xolodrilo, a mutant crocodile with an explorer hat and bright green tone; Balam, a jaguar with radiation-like markings and a more agile personality; and Lolita, a pink axolotl with luminous gills, which quickly became the favorite. Each needed animation states, consistent proportions, readable silhouettes and enough personality to feel alive on screen.\n\nAI can produce visually impressive images quickly, but consistency is harder. A character can change proportions between frames. Edges can look different. Lighting can shift. The work was less about generating a good image and more about building a reliable visual system from imperfect outputs.\n\nThe game had to work on desktop, mobile and Smart TV simultaneously. Mobile required touch controls and clear hit areas. Desktop needed keyboard input. TV was the hardest: Smart TV browsers and remote controls do not behave as predictably as standard web environments. I created an input manager that detected the context and adapted controls accordingly.`,
      es: `El juego necesitaba personajes originales con una base de fauna mexicana y una capa de mutante inspirada en la contaminación. Tres personajes se lanzaron: Xolodrilo, un cocodrilo mutante con sombrero de explorador y tono verde brillante; Balam, un jaguar con marcas parecidas a la radiación y una personalidad más ágil; y Lolita, una ajolote rosa con branquias luminosas, que rápidamente se convirtió en la favorita. Cada uno necesitaba estados de animación, proporciones consistentes, siluetas legibles y suficiente personalidad para sentirse vivo en pantalla.\n\nLa IA puede producir imágenes visualmente impresionantes rápidamente, pero la consistencia es más difícil. Un personaje puede cambiar proporciones entre fotogramas. Los bordes pueden verse diferentes. La iluminación puede cambiar. El trabajo era menos sobre generar una buena imagen y más sobre construir un sistema visual fiable a partir de outputs imperfectos.\n\nEl juego tenía que funcionar en escritorio, móvil y Smart TV simultáneamente. El móvil requería controles táctiles y áreas de golpe claras. El escritorio necesitaba entrada de teclado. La TV fue lo más difícil: los navegadores de Smart TV y los controles remotos no se comportan tan predeciblemente como los entornos web estándar. Creé un gestor de entrada que detectaba el contexto y adaptaba los controles en consecuencia.`,
    },
    howIApproached: {
      en: `For visual assets, I used AI tools to generate the first layer of characters, movements, backgrounds and textures. The useful part was the speed of exploration: testing several directions quickly, comparing results and deciding what had enough potential to refine. But I did not use the outputs as-is. Every character required manual work: cleaning edges, adjusting proportions, correcting frames, building spritesheets. Around 30–40% of each final sprite needed hands-on refinement. That was the difference between "this looks AI-generated" and "this feels like part of the same game."\n\nFor audio, I used AI-generated music for the first pass, then edited timing, loops, levels and effects manually. A loop can sound good in isolation and still feel wrong during gameplay if the pacing does not match the movement.\n\nThe game was built through vibe coding with React, Phaser and TypeScript. The structure included scenes for menu, character selection, gameplay, pause, game over and credits, plus systems for player movement, enemies, collectibles, scoring, responsive controls and an offline localStorage fallback for when the backend is unavailable. Vibe coding helped move faster, but it did not remove the need to understand what the system was doing.`,
      es: `Para los assets visuales, usé herramientas de IA para generar la primera capa de personajes, movimientos, fondos y texturas. La parte útil era la velocidad de exploración: probar varias direcciones rápidamente, comparar resultados y decidir qué tenía suficiente potencial para refinar. Pero no usé los outputs tal cual. Cada personaje requirió trabajo manual: limpiar bordes, ajustar proporciones, corregir fotogramas, construir spritesheets. Alrededor del 30–40% de cada sprite final necesitó refinamiento manual. Esa fue la diferencia entre "esto parece generado por IA" y "esto se siente como parte del mismo juego".\n\nPara el audio, usé música generada por IA para el primer pase, luego edité el timing, los bucles, los niveles y los efectos manualmente. Un bucle puede sonar bien en aislamiento y aún así sentirse incorrecto durante el juego si el ritmo no coincide con el movimiento.\n\nEl juego fue construido mediante vibe coding con React, Phaser y TypeScript. La estructura incluyó escenas para menú, selección de personaje, gameplay, pausa, game over y créditos, más sistemas para movimiento del jugador, enemigos, coleccionables, puntuación, controles responsive y un fallback offline de localStorage para cuando el backend no está disponible. El vibe coding ayudó a moverse más rápido, pero no eliminó la necesidad de entender qué hacía el sistema.`,
    },
    keyDecisions: {
      en: `AI as production layer, not creative authority. The most important decision was to use AI for acceleration, not for final judgment. AI generated options, but I decided the direction. AI created rough material, but I edited the final asset. AI helped write code, but I kept control over structure and behavior. The project needed to feel designed, not assembled from prompts.\n\nPolish over speed alone. I could have shipped faster by accepting more raw AI output. I chose to refine because the goal was not to prove that AI can generate assets. It was to create something that worked as a product. Craft is what makes AI-assisted work credible.\n\nMulti-platform from the beginning. Building for Smart TV added complexity, but it matched the real context where the game would be shown. If the classroom used a projector or TV, the product had to work there. A product is only successful if it works in the place where people actually use it.\n\nResilience as part of the UX. The game included a leaderboard, but I added a localStorage fallback so the experience would not break if the backend failed. That decision came from the same product mindset I use in larger digital projects: assume things can fail, then design the experience so the user is not punished for it.`,
      es: `IA como producción, no como criterio.\nLa IA fue útil para generar iteraciones rápidas, y a partir de ellas tomar la dirección con mayor potencial. Yo seleccionaba, editaba y descartaba. Esa diferencia fue clave para que el resultado no se sintiera ensamblado con prompts.\n\nRefinar aunque tomara más tiempo.\nMuchos assets se veían "suficientemente bien" al inicio, pero no tenían consistencia. Decidí invertir tiempo en pulido manual porque el objetivo era un juego que se sintiera terminado, independientemente de cómo se había hecho.\n\nDiseñar para tres plataformas desde el inicio.\nSmart TV agregaba complejidad, pero respondía al contexto real del proyecto. Si el juego se iba a presentar en un salón con pantalla o proyector, tenía que funcionar ahí.\n\nAgregar fallback offline.\nEl juego podía usar backend para leaderboard, pero no debía romperse si había un error de conexión. El fallback con localStorage hizo que la experiencia fuera más confiable.`,
    },
    outcome: {
      en: `The project went beyond the original school assignment. Built in six weeks, it shipped with 47 sprites, 18 audio files and 12 backgrounds, totaling around 8,500 lines of TypeScript across a React and Phaser codebase. It runs on web, mobile and Smart TV. It won a regional school prize and was later used as an example in high schools to explain AI-assisted creative production.\n\nMore importantly, it produced a concrete and playable demonstration of how I think about AI in design work. The game is live at elreydelpantano.figma.site and the source is open at github.com/josuebravodi/xolodrilo-game.`,
      es: `El juego se construyó en 6 semanas y terminó siendo más completo que el pedido original.\n\nIncluyó 47 sprites, 18 archivos de audio, 12 fondos y aproximadamente 8,500 líneas de código. Funciona en web, mobile y Smart TV.\n\nGanó un premio regional escolar y después fue usado como ejemplo en preparatorias para explicar cómo la IA puede apoyar procesos creativos.\n\nPero el resultado más importante fue lo que demostró: la IA puede acelerar muchísimo, pero el valor sigue estando en la dirección, el criterio y el pulido. Sin esa capa humana, el proyecto se habría quedado como demo.`,
    },
    learned: {
      en: `This project made my position on AI much clearer. The interesting question is not whether AI can replace creative work. The better question is how much more a designer can produce when AI becomes part of the studio, with the designer keeping the criteria, direction and responsibility.\n\nAI was useful for speed, exploration and production. The most human work was still judgment: deciding what was good, what was inconsistent, what needed more polish and what would actually work for the user. That part does not get compressed.\n\nIt also reminded me that systems thinking matters even in a playful project. The hardest parts were not the individual images or sounds. The hardest parts were making everything work together across devices, states, inputs and failure scenarios. That is where design stops being just output and becomes product thinking.`,
      es: `Este proyecto me ayudó a aterrizar mi postura sobre IA en diseño.\n\nLa conversación ya no se trata sobre si la IA nos remplazará como diseñadores, sino como apropiarnos de estas herramientas para lograr resultados con mayor alcance.\n\nTambién aprendí que la parte más difícil no siempre está en generar cosas. La IA puede producir imágenes, sonidos y código rápido. Lo difícil es hacer que todo funcione junto: mismos personajes, misma lógica visual, distintos inputs, distintas plataformas, estados de error y una experiencia que no se rompa.\n\nAhí es donde el diseño vuelve a ser criterio de producto, no solo output visual.`,
    },
    metrics: [
      { value: '6 wks',  label: { en: 'concept to shipped',  es: 'de concepto a producto' } },
      { value: '~8,500', label: { en: 'lines of TypeScript', es: 'líneas de TypeScript' } },
      { value: '77',     label: { en: 'original assets',     es: 'assets originales' } },
    ],
    tags: ['AI-assisted Design', 'Vibe Coding', 'Higgsfield', 'Kling', 'Adobe Firefly', 'Game Design', 'Multi-platform UX'],
    imageBg: 'from-orange-900 to-red-800',
    images: {
      hero: [
        '/images/projects/xolodrilo-designing-a-game-with-ai/01-hero-01.webp',
        '/images/projects/xolodrilo-designing-a-game-with-ai/01-hero-02.webp',
        '/images/projects/xolodrilo-designing-a-game-with-ai/01-hero-03.webp',
        '/images/projects/xolodrilo-designing-a-game-with-ai/01-hero-04.webp',
      ],
      processMap: '/images/projects/xolodrilo-designing-a-game-with-ai/02-process-map.webp',
      artifacts:  '/images/projects/xolodrilo-designing-a-game-with-ai/03-artifact-detail.webp',
      impact:     '/images/projects/xolodrilo-designing-a-game-with-ai/04-impact-chart.webp',
    },
  },
];
